image: docker:latest

services:
 - docker:dind

stages:
 - build

variables:
 DOCKER_DRIVER: overlay2

build:
 stage: build
 script:
    - docker build -t my-app:$CI_PIPELINE_ID ./backend
    - docker build -t my-frontend:$CI_PIPELINE_ID ./frontend
 only:
    - main
