# image: docker:latest

# services:
#  - docker:dind

# stages:
#  - build

# variables:
#  DOCKER_DRIVER: overlay2

# build:
#  stage: build
#  script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - docker build -t $CI_REGISTRY_IMAGE:latest ./backend
#     - docker build -t $CI_REGISTRY_IMAGE:latest ./frontend
#     - docker push $CI_REGISTRY_IMAGE:latest


stages:
 - build

variables:
 IMAGE_TAG: $CI_PIPELINE_ID

build_api:
 stage: build
 image: docker:latest
 services:
    - docker:dind
 script:
    - docker build -t my-api:$IMAGE_TAG ./backend
    - docker push my-api:$IMAGE_TAG

build_frontend:
 stage: build
 image: docker:latest
 services:
    - docker:dind
 script:
    - docker build -t my-frontend:$IMAGE_TAG ./frontend
    - docker push my-frontend:$IMAGE_TAG
